import{S as v,a as P,i as c}from"./assets/vendor-CRCB-GUD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();let f;function $(e){const r=document.querySelector("#gallery"),a=e.map(({webformatURL:s,largeImageURL:t,tags:o,likes:i,views:w,comments:q,downloads:S})=>`
    <a class="gallery-link" href="${t}">
    <img src="${s}" class="gallery-image" alt="${o}" loading="lazy"/>
    <div class="inform">
    <p><b>Likes</b>: ${i}</p>
    <p><b>Views</b>: ${w}</p>
    <p><b>Comments</b>: ${q}</p>
    <p><b>Downloads</b>: ${S}</p>
    </div>
    </a>
    `).join("");r.insertAdjacentHTML("beforeend",a),f?f.refresh():f=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function E(){document.querySelector(".gallery").innerHTML=""}const l="is-hidden";function y(e){e.classList.add(l)}function T(e){e.classList.remove(l)}function h(e,r){e.disabled=!0,r.classList.remove(l)}function m(e,r){e.disabled=!1,r.classList.add(l)}const O="46312976-051d72b45cfaa84800b7fd140";async function M(e,r=1){const a=`https://pixabay.com/api/?key=${O}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{return(await P.get(a)).data}catch{c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}}let u=1,g="";const p=document.querySelector(".form"),d=document.querySelector(".loader"),n=document.querySelector(".load-more");y(n);m(n,d);p.addEventListener("submit",N);async function N(e){e.preventDefault(),E();const r=e.currentTarget.elements.query.value.trim();if(!r)return L("❌ Please enter a search query");h(n,d),g=r,u=1,await b()}async function b(){try{const e=await M(g,u);if(e.hits.length===0)return H("Sorry, there are no images matching your search query.");$(e.hits),x(e.totalHits)}catch{B()}finally{m(n,d),p.reset()}}function x(e){e>u*15?T(n):(y(n),I("We're sorry, but you've reached the end of search results."))}function B(e){L("❌ No pictures found")}n.addEventListener("click",async()=>{h(n,d),y(n),u+=1,await b(),D()});function D(){const{height:e}=document.querySelector(".gallery").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function L(e){c.error({title:"Error",message:e})}function H(e){c.warning({title:"No Results",message:e})}function I(e){c.info({title:"End of Results",message:e})}
//# sourceMappingURL=index.js.map
